Product/urls.py
from django.urls import path
from .views import *

app_name = "Product"
urlpatterns = [
    path('new/', new, name="new"),
    path('create/', create, name="create"),
    path('', main, name="main"),
    path('show/<int:id>', show, name="show"),
    path('update/<int:id>/', update, name="update"),
    path('delete/<int:id>/', delete, name="delete"),
    
]

shopping/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views
from django.conf import settings 
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.main, name="main"),
    path('product/', include('Product.urls')),
    path('accounts/', include('allauth.urls')),

]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Product/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.
class Post(models.Model) :
    title = models.CharField(max_length=50, null=False)
    content = models.TextField()
    price = models.IntegerField(verbose_name = "상품가격", null=True)
    stock = models.IntegerField(verbose_name = "상품재고", null=True)
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)
    image = models.ImageField(upload_to= 'images/', null=True)
    user = models.ForeignKey(User, on_delete = models.CASCADE, null=True)


class Comment(models.Model):
    content = models.TextField()
    grade = models.IntegerField(verbose_name="평점", null=True)
    writer = models.ForeignKey(User, on_delete = models.CASCADE)
    post = models.ForeignKey(Post, on_delete = models.CASCADE, related_name = 'comment')
    created_at = models.DateTimeField(auto_now_add = True)
    updated_at = models.DateTimeField(auto_now = True)

Product/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post


def new(request):
    return render(request, 'Product/new.html')

def create(request):
    if request.method == "POST" :
        title = request.POST.get('title')
        content = request.POST.get('content')
        image = request.FILES.get('image')
        user = request.user
        price = request.POST.get('price')
        stock = request.POST.get('stock')
        Post.objects.create(title=title, content=content, image=image, user=user, price=price, stock=stock)
        return redirect('Product:main')

def main(request) :
    Product = Post.objects.all()
    return render(request, 'Product/main.html', {'Product':Product})

def show(request, id):
    post = Post.objects.get(pk=id)
    return render(request, 'Product/show.html', {'post':post})


def update(request, id):
    post = get_object_or_404(Post, pk=id)
    if request.method == "POST":
        post.title = request.POST['title']
        post.content = request.POST['content']
        post.image = request.FILES.get('image')
        post.price = request.POST['price']
        post.stock = request.POST['stock']
        post.save()
        return redirect('Product:show', post.id)
    return render(request, 'Product/update.html', {"post":post})

def delete(request, id):
    post = get_object_or_404(Post, pk=id)
    post.delete()
    return redirect("Product:main")

shopping/views.py
from django.shortcuts import render


def main(request):
    return render(request, 'main.html')

Product/templates/Product/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
{% if user.is_authenticated %} 
<div class="container">
    <h1>LIKELION의 모든 상품!</h1>
    <a href="{% url 'Product:new'%}" class="btn btn-primary">상품 판매하기</a>
    <div class="row">
        {% for post in Product %}
        <div class="col-md-4 col-12">
            <div class="card" style="width: 18rem; margin-top: 20px;">
                <div class="card-body">
                    <h5 class="card-title">상품명 : {{ post.title }}</h5>
                    <p>상품 가격 : {{ post.price }}</p>
                    <p>{{ post.stock }}개 남았습니다.</p>
                    <a href="{% url 'Product:show' post.pk %}" class="btn btn-primary">자세히 보기</a>
                </div>
            </div>
        </div>
        {% endfor %}
    </div>
</div>
{% else %}
    <h3>로그인 후 이용이 가능합니다.</h3>
    <a href="{% url 'account_login' %}" class="btn btn-warning">로그인</a>
    <a href="{% url 'account_signup' %}" class="btn btn-warning">회원가입</a>

{% endif %}
{% endblock %}

Product/templates/Product/new.html
{% extends 'base.html' %}
{% block content %}

<div class="container">
    <h1>
        새로운 상품 판매하기
    </h1>
    <form action="{% url 'Product:create' %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="title">
        </div>
        <div class="form-group">
            <label>상품 설명</label>
            <textarea class="form-control" name="content"></textarea>
        </div>
        <div class="form-group">
            <label>상품 가격</label>
            <textarea class="form-control" name="price">{{post.price}}</textarea>
        </div>
        <div class="form-group">
            <label>상품 재고</label>
            <textarea class="form-control" name="stock">{{post.stock}}</textarea>
            <input type="file" name="image">
        </div>
        <input type="submit" value="글 작성" class="btn btn-outline-primary">
    </form> 
</div>
{% endblock %}

Product/templates/Product/show.html
{% extends 'base.html' %}
{% block content %}
{% include 'shared/_navbar.html' %}
{% if post.image %}
<img src = "{{post.image.url}}">
{% endif %}
<h3>상품명 : {{ post.title }} </h3><br>
{% if post.user %}
<h3>판매자 : {{ post.user }}</h3><br>
{% else %}
<h3>판매자 : 알 수 없음</h3><br>
{% endif %}
<h3>상품 설명 : {{ post.content }} </h3><br>
<h3>가격(원) : {{ post.price }}</h3><br>
<h3>재고 : {{ post.stock }}</h3><br>
<h3>작성 시각 : {{ post.created_at }} </h3><br>
<h3>수정 시각 : {{ post.updated_at }} </h3><br>


{% if user == post.user %}
        <a href = "{% url 'Product:update' post.pk %}">수정하기</a>
        <a href = "{% url 'Product:delete' post.pk %}">삭제하기</a>
{% endif %}
{% endblock %}

Product/templates/Product/update.html
{% extends 'base.html' %}

{% block content %}
{% include 'shared/_navbar.html' %}
<div class="container">
    <h1>
        수정하기
    </h1>
    <form action="{% url 'Product:update' post.id %}" method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        <div class="form-group">
            <label>상품명</label>
            <input type="text" class="form-control" name="title" value="{{post.title}}"> 
        </div>
        <div class="form-group">
            <label>상품 설명서</label>
            <textarea class="form-control" name="content">{{post.content}}</textarea>
        </div>
        <div class="form-group">
            <label>상품 가격</label>
            <textarea class="form-control" name="price">{{post.price}}</textarea>
        </div>
        <div class="form-group">
            <label>상품 재고</label>
            <textarea class="form-control" name="stock">{{post.stock}}</textarea>
            <input type="file" name="image">
        </div>
        <input type="submit" value="글 수정" class="btn btn-outline-primary">
    </form>
</div>
{% endblock %}

shopping/templates/base.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <!-- Bootstrap CSS -->
    <link rel="stylesheet" href = "https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous">
    <link rel="stylesheet" href = "{% static 'css/project.css' %}">
    <link href="https://fonts.googleapis.com/css2?family=Single+Day&display=swap" rel="stylesheet">
    <title>Beautiful City</title>
  </head>
  <body>
  
      {% block content %}
      {% endblock %}

    <!-- Optional JavaScript -->
    <!-- jQuery first, then Popper.js, then Bootstrap JS -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/js/bootstrap.min.js" integrity="sha384-OgVRvuATP1z7JjHLkuOU7Xw704+h835Lr+6QL9UvYjZE3Ipu6Tp75j7Bh/kR0JKI" crossorigin="anonymous"></script>
  </body>
</html>

shopping/templates/main.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
{% include 'shared/_navbar.html' %}
<h1>LIKELION SHOPPING</h1>
<img src="{% static 'images/멋쟁이 사자처럼.jpg' %}" alt="LIKELION LOGO">
{% endblock %}

shopping/templates/shared/_navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="{% url 'main' %}">LIKELION</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav mr-auto">
        <li class="nav-item active">
          <a class="nav-link" href="{% url 'main' %}">Home <span class="sr-only">(current)</span></a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'Product:main' %}">Product</a>
        </li>
        {% if user.is_authenticated %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_logout' %}">로그아웃</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_change_password' %}">비밀번호 변경</a>
        </li>
        {% else %}
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_login' %}">로그인</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'account_signup' %}">회원가입</a>
        </li>
        {% endif %}
      </ul>
    </div>
  </nav>